import { StyleSheet, Dimensions, Animated } from "react-native";

import { COLORS, FONT, SIZES } from "../../../constants";

const screenHeight = Dimensions.get('window').height;
const screenWidth = Dimensions.get('window').width;

const styles = StyleSheet.create({
  container: {
    marginTop: SIZES.xLarge,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: SIZES.small,
  },
  headerTitle: {
    fontSize: SIZES.large,
    fontFamily: FONT.medium,
    color: COLORS.primary,
  },
  headerBtn: {
    fontSize: SIZES.medium,
    fontFamily: FONT.medium,
    color: COLORS.gray,
  },
  cardsContainer: {
    marginTop: SIZES.medium,
    gap: SIZES.small,
  },
  buttonContainer: { 
    position: "absolute",
    padding: 15, 
    alignItems: "center", 
    borderRadius: 20,
    height: '100%',
    width: '100%', 
    opacity: 1.0,
    zIndex: 100,
  },
  loginView: {
    display: 'flex',
    // backgroundColor: 'green',
    flexDirection: 'column',
    alignItems: 'center',
    objectFit: 'contain',
    height: '60%',
    justifyContent: 'center',
    borderRadius: 15,
    bottom: '-13%',
  },
  image: {
    // Add styles for the ImageBackground here
    flex: 1, // You may need to adjust this depending on your layout
    height: screenHeight,
    width: screenWidth,
    justifyContent: 'center',
    alignItems: 'center', 
  },
  signinbutton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '85%',
    height: 65,
    bottom: '-93%',
    marginTop: '10%',
    paddingVertical: 11,
    paddingHorizontal: 32,
    borderRadius: 10,
    elevation: 1,
    borderWidth: 2,
    backgroundColor: '#1281D1',
    borderColor: '#1281D1',
  },
  signupbutton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '85%',
    // marginTop: '0%',
    margin: 40,
    paddingVertical: 21,
    paddingHorizontal: 32,
    borderRadius: 10,
    elevation: 0,
    // backgroundColor: 'invisible',
    color: 'white',
    borderWidth: 2,
    backgroundColor: '#181919',
    borderColor: 'white',
  },
  buttonsViewcontainer: {
    position: 'absolute',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: -10,
    justifyContent: 'space-evenly',
    // backgroundColor: 'green',
    width: '100%',
    height: '80%',
    zIndex: 1000,
  },
  signintext: {
    fontSize: 23,
    lineHeight: 26,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: 'white',
  },
  signuptext: {
    fontSize: 18,
    lineHeight: 26,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: 'white',
  },
  textor: {
    // backgroundColor: 'black',
    // padding: '5%',
    fontSize: 18,
    lineHeight: 26,
    fontWeight: '400',
    letterSpacing: 0.25,
    color: 'white',
  },
  Viewtextor: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    width: '10%',
    height: '10%',
    color: 'black',
    zIndex: 1000,
  },
  Selectstyle: {
    backgroundColor: 'white',
  },
  dropdown2BtnStyle: {
    margin: 40,
    width: '85%',
    height: 65,
    backgroundColor: '#181919',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'white',
  },
  dropdown2BtnTxtStyle: {
    color: '#FFF',
    textAlign: 'left',
    fontWeight: 'bold',
  },
  dropdown2DropdownStyle: {
    backgroundColor: '#181919',
    borderRadius: 12,
    height: 165,
  },
  dropdown2RowStyle: {backgroundColor: '#181919', borderBottomColor: '#181919'},
  dropdown2RowTxtStyle: {
    color: '#FFF',
    textAlign: 'left',
    padding: 15,
    fontWeight: 'bold',
  },
  shadow: {
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 10,
  },
  username: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '85%',
    height: 65,
    // marginTop: '0%',
    margin: 40,
    paddingVertical: 21,
    paddingHorizontal: 22,
    borderRadius: 10,
    elevation: 0,
    // backgroundColor: 'invisible',
    color: 'white',
    borderWidth: 2,
    backgroundColor: '#181919',
    borderColor: 'white',
    textAlign: 'left',
    fontWeight: 'bold',
    fontSize: 18,
  },
  forgottext:{
    color: 'white',
  },
  forgottextview: {
    display: 'flex',
    width: '85%',
    // backgroundColor: 'green',
    bottom: '-83%',
    alignItems: 'flex-end',
    
  },
  rememberview: {
    display: 'flex',
    flexDirection: 'row',
    objectFit: 'contain',
    margin: 'auto',
    width: '85%',
    bottom: '-73%',
    alignItems: 'flex-start',
  },
  switch: {
    transform: [{ scaleX: .8 }, { scaleY: .8 }]
    // width: '20%',
    // backgroundColor: 'white',
  },
  remembertext: {
    // backgroundColor: 'green',
    padding: 6,
    textAlignVertical: 'center',
    height: '100%',
    textAlign: 'center',
    color: 'white',
    fontSize: 15,
  },
  donthaveview: {
    display: 'flex',
    width: '85%',
    // backgroundColor: 'green',
    bottom: '-100%',
    alignItems: 'center',
  },
  donthavetext:{
    color: 'white',
  },
//   headerTitle: {color: '#000', fontWeight: 'bold', fontSize: 16},
//   saveAreaViewContainer: {flex: 1, backgroundColor: '#FFF'},
//   viewContainer: {flex: 1, width: 50, backgroundColor: '#FFF'},
//   scrollViewContainer: {
//     flexGrow: 1,
//     justifyContent: 'space-between',
//     alignItems: 'center',
//     paddingVertical: '10%',
//     paddingBottom: '20%',
//   }
});

export default styles;
