import { StyleSheet, Dimensions, Animated } from "react-native";

import { COLORS, FONT, SIZES } from "../../../constants";

const screenHeight = Dimensions.get('window').height;
const screenWidth = Dimensions.get('window').width;

const styles = StyleSheet.create({
  image: {
    // Add styles for the ImageBackground here // You may need to adjust this depending on your layout
    position: 'absolute',
    height: screenHeight,
    width: screenWidth,
    justifyContent: 'center',
    alignItems: 'center', 
    zIndex: -1,
  },
  baseimage: {
    position: 'sticky',
    width: 'auto',
    height: 100,
    marginBottom: '0%',
    // backgroundColor: 'green',

  },
  homepageview: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    // backgroundColor: 'red',
    marginTop: '7%',
    gap: 18,
    height: screenHeight/2.3,
    width: screenWidth,
    // backgroundColor: 'green',
  },
  usernameview: {
    width: '90%',
    height: '8%',
    // backgroundColor: 'red',
    textAlignVertical: 'center',
    top: 5,
  },
  usernametext: {
    color: 'white',
    textAlign: 'left',
    top: '0%',
    fontSize: 23,
    fontWeight: "bold",

  },
  searchbarview: {
    width: '90%',
    top: '0%',
    // backgroundColor: 'blue',
  },
  searchbar: {
    borderRadius: 20,
    borderColor: '#626363',
    opacity: 1,
    borderWidth: 1,
    backgroundColor: "rgba(238, 238, 238, 0.1)",
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOffset: {
    width: 0,
    height: 0,
    shadowOpacity: 1,
    },
  },
  filteredstockview: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '90%',
    height: '15%',
    // backgroundColor: 'yellow',
  },
  filtered: {
    height: '100%',
    width: '45%',
    // backgroundColor: 'red',
    marginHorizontal: 10,
    borderRadius: 15,
    borderColor: 'white',
    opacity: 1,
    borderWidth: 1,
    backgroundColor: "rgba(238, 238, 238, 0.1)",
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOffset: {
    width: 0,
    height: 0,
    shadowOpacity: 1,}
  },
  filteredtext: {
    color: 'white',
    // backgroundColor: 'red',
    padding: 4,
    fontWeight: 'bold',
    marginLeft: 4,
    fontSize: 15,
  },
  fundsview: {
    display: 'flex',
    flexDirection: 'column',
    width: '90%',
    height: '30%',
    // backgroundColor: 'blue',
  },
  fundstextview: {
    display: 'flex',
    height: '30%',
    // backgroundColor: 'green',
  },
  fundstext: {
  color: 'white',
  fontWeight: "bold",
  fontSize: 18,
  textAlignVertical: 'center',
  textAlign: "left",
  verticalAlign: "middle",
  // backgroundColor: 'red',
  },
  fundsboxes: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    height: '70%',
    width: '100%',
  },
  boxes: {
    height: '100%',
    width: '45%',
    marginHorizontal: 10,
    height: '100%',
    width: '45%',
    // backgroundColor: 'red',
    marginHorizontal: 10,
    borderRadius: 20,
    borderColor: '#626363',
    opacity: 1,
    borderWidth: 2,
    backgroundColor: "rgba(238, 238, 238, 0.1)",
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOffset: {
    width: 0,
    height: 0,
    shadowOpacity: 1,}
  },
  boxestext: {
    color: 'white',
    // backgroundColor: 'red',
    padding: 7,
    fontWeight: 'bold',
    fontSize: 15,
    textAlign: 'center',
  },
  boxestext2: {
    color: 'white',
    // backgroundColor: 'red',
    padding: 7,
    fontSize: 15,
    textAlign: 'center',
  },
  marketwatchview: {
    display: 'flex',
    flexDirection: 'column',
    alignSelf: 'center',
    width: '90%',
    height: screenHeight/1.6,
    // backgroundColor: 'red',
    marginTop: "-40%",
  },
  markettextview: {
    display: 'flex',
    height: '10%',
    // backgroundColor: 'green',
  },
  markettext: {
  color: 'white',
  fontWeight: "bold",
  fontSize: 18,
  textAlignVertical: 'center',
  textAlign: "left",
  verticalAlign: "middle",
  // backgroundColor: 'red',
  },
  martketHscroll: {
    width: '100%',
    height: '7%',
    marginTop: -6,
    // backgroundColor: 'blue',
  },
  marketoption1: {
    height: '100%',
    width: 90,
    marginHorizontal: 10,
    // backgroundColor: 'red',
    marginHorizontal: 5,
    borderRadius: 10,
    borderColor: 'white',
    opacity: 1,
    borderWidth: 1.3,
    backgroundColor: "rgba(238, 238, 238, 0.1)",
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOffset: {
    width: 0,
    height: 0,
    shadowOpacity: 1,}
  },
  marketoptiontext: {
    color: 'white',
    // backgroundColor: 'red',
    padding: 7,
    fontWeight: '500',
    fontSize: 13,
    textAlign: 'center',
  },
  martketHscroll2: {
    width: '100%',
    height: screenHeight,
    alignItems: 'center',
    display: 'flex',
    marginTop: 15,
    // backgroundColor: 'green',
  },
  marketstocksview: {
    width: '100%',
    height: '81%',
    display: 'flex',
    marginTop: 20,
    backgroundColor: 'green',
  },
  marketstock1: {
    width: '100%',
    height: '81%',
    marginHorizontal: 10,
    // backgroundColor: 'red',
    marginHorizontal: 9,
    borderRadius: 10,
    borderColor: '#626363',
    opacity: 1,
    borderWidth: 2,
    backgroundColor: "rgba(238, 238, 238, 0.1)",
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOffset: {
    width: 0,
    height: 0,
    shadowOpacity: 1,}
  },
  marketoption2: {
    width: '100%',
    height: 55,
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 12,
    // marginVertical: 0,
    // backgroundColor: 'red',
    borderRadius: 10,
    borderColor: 'white',
    opacity: 1,
    borderWidth: 1,
    backgroundColor: "rgba(238, 238, 238, 0.1)",
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOffset: {
    width: 0,
    height: 0,
    shadowOpacity: 1,}
  },
  marketstockleft: {
    height: '100%',
    width: '50%',
    // backgroundColor: 'yellow',
  },
  marketstocklefttop: {
    display: 'flex',
    flexDirection: 'row',
    height: '100%',
    width: '50%',
    // backgroundColor: 'yellow',
  },
  marketstockright: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    height: '100%',
    width: '50%',
    // backgroundColor: 'yellow',
  },
  marketstocktext: {
    color: 'white',
    // backgroundColor: 'red',
    fontWeight: '500',
    fontSize: 12,
    marginTop: 10,
    marginLeft: 10,
    textAlign: 'left',
    textAlignVertical: 'middle',
  },
  marketstockpercent: {
    color: '#007000',
    // backgroundColor: 'red',
    fontWeight: '500',
    fontSize: 12,
    marginTop: 4,
    marginLeft: 10,
    textAlign: 'left',
    textAlignVertical: 'middle',
  },
  marketstocktexttop: {
    color: 'white',
    // backgroundColor: 'red',
    fontWeight: '500',
    fontSize: 12,
    marginTop: -3,
    marginLeft: 7,
    textAlign: 'left',
    textAlignVertical: 'middle',
  },
  marketstockpercenttop: {
    color: '#007000',
    // backgroundColor: 'red',
    fontWeight: '500',
    fontSize: 9,
    marginTop: -1,
    marginLeft: 3,
    textAlign: 'left',
    textAlignVertical: 'middle',
  },
  marketstockpercenttop2: {
    color: '#D2222D',
    // backgroundColor: 'red',
    fontWeight: '500',
    fontSize: 9,
    marginTop: -1,
    marginLeft: 3,
    textAlign: 'left',
    textAlignVertical: 'middle',
  },
  marketstocklowhigh: {
    height: '70%',
    width: '50%',
    marginHorizontal: 10,
    marginRight: 30,
    // backgroundColor: 'red',
    marginHorizontal: 0,
    borderRadius: 10,
    borderColor: 'white',
    opacity: 1,
    borderWidth: 1,
    backgroundColor: "rgba(238, 238, 238, 0.1)",
    shadowColor: "rgba(0, 0, 0, 0.1)",
    shadowOffset: {
    width: 0,
    height: 0,
    shadowOpacity: 1,}
  },
  marketstocklowhightext: {
    color: 'white',
    // backgroundColor: 'red',
    padding: 4,
    fontWeight: '500',
    fontSize: 10,
    textAlign: 'center',
  },
  marketstocklowhightext2: {
    color: '#1281D1',
    // backgroundColor: 'red',
    padding: 0,
    fontWeight: '500',
    fontSize: 8,
    textAlign: 'center',
    marginTop: -4,
  }
  

});

export default styles;
